/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssignTicketRequest
 */
export interface AssignTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof AssignTicketRequest
     */
    ticketId: string;
    /**
     * 
     * @type {string}
     * @memberof AssignTicketRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the AssignTicketRequest interface.
 */
export function instanceOfAssignTicketRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ticketId" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function AssignTicketRequestFromJSON(json: any): AssignTicketRequest {
    return AssignTicketRequestFromJSONTyped(json, false);
}

export function AssignTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignTicketRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ticketId': json['ticketId'],
        'userId': json['userId'],
    };
}

export function AssignTicketRequestToJSON(value?: AssignTicketRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ticketId': value.ticketId,
        'userId': value.userId,
    };
}

