/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelUser } from './ModelUser';
import {
    ModelUserFromJSON,
    ModelUserFromJSONTyped,
    ModelUserToJSON,
} from './ModelUser';

/**
 * 
 * @export
 * @interface DashboardResponse
 */
export interface DashboardResponse {
    /**
     * 
     * @type {Array<ModelUser>}
     * @memberof DashboardResponse
     */
    users: Array<ModelUser>;
}

/**
 * Check if a given object implements the DashboardResponse interface.
 */
export function instanceOfDashboardResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function DashboardResponseFromJSON(json: any): DashboardResponse {
    return DashboardResponseFromJSONTyped(json, false);
}

export function DashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(ModelUserFromJSON)),
    };
}

export function DashboardResponseToJSON(value?: DashboardResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': ((value.users as Array<any>).map(ModelUserToJSON)),
    };
}

