/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DashboardResponse } from './DashboardResponse';
import {
    DashboardResponseFromJSON,
    DashboardResponseFromJSONTyped,
    DashboardResponseToJSON,
} from './DashboardResponse';

/**
 * 
 * @export
 * @interface DashboardResponseResponse
 */
export interface DashboardResponseResponse {
    /**
     * 
     * @type {number}
     * @memberof DashboardResponseResponse
     */
    errorCode?: number;
    /**
     * 
     * @type {string}
     * @memberof DashboardResponseResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {DashboardResponse}
     * @memberof DashboardResponseResponse
     */
    result?: DashboardResponse;
}

/**
 * Check if a given object implements the DashboardResponseResponse interface.
 */
export function instanceOfDashboardResponseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DashboardResponseResponseFromJSON(json: any): DashboardResponseResponse {
    return DashboardResponseResponseFromJSONTyped(json, false);
}

export function DashboardResponseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardResponseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'result': !exists(json, 'result') ? undefined : DashboardResponseFromJSON(json['result']),
    };
}

export function DashboardResponseResponseToJSON(value?: DashboardResponseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
        'errorMessage': value.errorMessage,
        'result': DashboardResponseToJSON(value.result),
    };
}

