/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuidResponse
 */
export interface GuidResponse {
    /**
     * 
     * @type {number}
     * @memberof GuidResponse
     */
    errorCode?: number;
    /**
     * 
     * @type {string}
     * @memberof GuidResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GuidResponse
     */
    result?: string;
}

/**
 * Check if a given object implements the GuidResponse interface.
 */
export function instanceOfGuidResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GuidResponseFromJSON(json: any): GuidResponse {
    return GuidResponseFromJSONTyped(json, false);
}

export function GuidResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function GuidResponseToJSON(value?: GuidResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
        'errorMessage': value.errorMessage,
        'result': value.result,
    };
}

