/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelTicket } from './ModelTicket';
import {
    ModelTicketFromJSON,
    ModelTicketFromJSONTyped,
    ModelTicketToJSON,
} from './ModelTicket';

/**
 * 
 * @export
 * @interface InsertTicketRequest
 */
export interface InsertTicketRequest {
    /**
     * 
     * @type {ModelTicket}
     * @memberof InsertTicketRequest
     */
    ticket: ModelTicket;
}

/**
 * Check if a given object implements the InsertTicketRequest interface.
 */
export function instanceOfInsertTicketRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ticket" in value;

    return isInstance;
}

export function InsertTicketRequestFromJSON(json: any): InsertTicketRequest {
    return InsertTicketRequestFromJSONTyped(json, false);
}

export function InsertTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsertTicketRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ticket': ModelTicketFromJSON(json['ticket']),
    };
}

export function InsertTicketRequestToJSON(value?: InsertTicketRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ticket': ModelTicketToJSON(value.ticket),
    };
}

