/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelTicketModelWrapper } from './ModelTicketModelWrapper';
import {
    ModelTicketModelWrapperFromJSON,
    ModelTicketModelWrapperFromJSONTyped,
    ModelTicketModelWrapperToJSON,
} from './ModelTicketModelWrapper';

/**
 * 
 * @export
 * @interface ModelTicketModelWrapperResponse
 */
export interface ModelTicketModelWrapperResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelTicketModelWrapperResponse
     */
    errorCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelTicketModelWrapperResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {ModelTicketModelWrapper}
     * @memberof ModelTicketModelWrapperResponse
     */
    result?: ModelTicketModelWrapper;
}

/**
 * Check if a given object implements the ModelTicketModelWrapperResponse interface.
 */
export function instanceOfModelTicketModelWrapperResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelTicketModelWrapperResponseFromJSON(json: any): ModelTicketModelWrapperResponse {
    return ModelTicketModelWrapperResponseFromJSONTyped(json, false);
}

export function ModelTicketModelWrapperResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelTicketModelWrapperResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'result': !exists(json, 'result') ? undefined : ModelTicketModelWrapperFromJSON(json['result']),
    };
}

export function ModelTicketModelWrapperResponseToJSON(value?: ModelTicketModelWrapperResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
        'errorMessage': value.errorMessage,
        'result': ModelTicketModelWrapperToJSON(value.result),
    };
}

