/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelTicket } from './ModelTicket';
import {
    ModelTicketFromJSON,
    ModelTicketFromJSONTyped,
    ModelTicketToJSON,
} from './ModelTicket';

/**
 * 
 * @export
 * @interface ModelTicketModelWrapper
 */
export interface ModelTicketModelWrapper {
    /**
     * 
     * @type {Array<ModelTicket>}
     * @memberof ModelTicketModelWrapper
     */
    results: Array<ModelTicket>;
    /**
     * 
     * @type {number}
     * @memberof ModelTicketModelWrapper
     */
    total: number;
}

/**
 * Check if a given object implements the ModelTicketModelWrapper interface.
 */
export function instanceOfModelTicketModelWrapper(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "results" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ModelTicketModelWrapperFromJSON(json: any): ModelTicketModelWrapper {
    return ModelTicketModelWrapperFromJSONTyped(json, false);
}

export function ModelTicketModelWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelTicketModelWrapper {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ModelTicketFromJSON)),
        'total': json['total'],
    };
}

export function ModelTicketModelWrapperToJSON(value?: ModelTicketModelWrapper | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': ((value.results as Array<any>).map(ModelTicketToJSON)),
        'total': value.total,
    };
}

