/* tslint:disable */
/* eslint-disable */
/**
 * HelpDeskAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TicketStatus } from './TicketStatus';
import {
    TicketStatusFromJSON,
    TicketStatusFromJSONTyped,
    TicketStatusToJSON,
} from './TicketStatus';

/**
 * 
 * @export
 * @interface UpdateTicketRequest
 */
export interface UpdateTicketRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTicketRequest
     */
    id: string;
    /**
     * 
     * @type {TicketStatus}
     * @memberof UpdateTicketRequest
     */
    status: TicketStatus;
}

/**
 * Check if a given object implements the UpdateTicketRequest interface.
 */
export function instanceOfUpdateTicketRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function UpdateTicketRequestFromJSON(json: any): UpdateTicketRequest {
    return UpdateTicketRequestFromJSONTyped(json, false);
}

export function UpdateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTicketRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'id': json['id'],
        'status': TicketStatusFromJSON(json['status']),
    };
}

export function UpdateTicketRequestToJSON(value?: UpdateTicketRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'id': value.id,
        'status': TicketStatusToJSON(value.status),
    };
}

