/* tslint:disable */
/* eslint-disable */
/**
 * HelpDesk API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelTicket } from './ModelTicket';
import {
    ModelTicketFromJSON,
    ModelTicketFromJSONTyped,
    ModelTicketToJSON,
} from './ModelTicket';

/**
 * 
 * @export
 * @interface UpsertTicketsRequest
 */
export interface UpsertTicketsRequest {
    /**
     * 
     * @type {Array<ModelTicket>}
     * @memberof UpsertTicketsRequest
     */
    tickets: Array<ModelTicket>;
}

/**
 * Check if a given object implements the UpsertTicketsRequest interface.
 */
export function instanceOfUpsertTicketsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tickets" in value;

    return isInstance;
}

export function UpsertTicketsRequestFromJSON(json: any): UpsertTicketsRequest {
    return UpsertTicketsRequestFromJSONTyped(json, false);
}

export function UpsertTicketsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertTicketsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tickets': ((json['tickets'] as Array<any>).map(ModelTicketFromJSON)),
    };
}

export function UpsertTicketsRequestToJSON(value?: UpsertTicketsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tickets': ((value.tickets as Array<any>).map(ModelTicketToJSON)),
    };
}

